addr: localhost:8080
log_level: info
store_interval: 300s
file_storage_path: /tmp/metrics-db.json
restore: true
poll_interval: 2s
report_interval: 10s
database_dsn: host=0.0.0.1 user=postgres password=351762 dbname=getmetrics sslmode=disable